config/routes.rb
Rails.application.routes.draw do


  resources :categories
  resources :articles do #Generará todas las rutas del CRUD
    resources :comments, only: [:create, :update, :destroy, :show] #Hacemos esto para que no existan los comentarios por si solo, sinó que solo para los artículos
  end
  devise_for :users


  root 'welcome#index'

  get "/dashboard", to: "welcome#dashboard"
  get "/about_me", to: "welcome#about_me"
  put "/articles/:id/publish", to: "articles#publish"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/partials/_categoriesW.html.erb
<div class="card my-4">
  <h5 class="card-header">Categorías</h5>
  <div class="card-body">
    <div class="row">
      <% @categories.each do |category| %>
      <div class="col-lg-6">
        <ul class="list-unstyled mb-0">
          <li>
            <%= link_to category.name, category %>
          </li>
        </ul>
      </div>
      <%end%>
    </div>
  </div>
</div>

app/views/partials/_navbar.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav">
        <li class="home"><%= link_to "Matías Daza", root_path %></li>
        <li><%= link_to "Blog", articles_path%></li>
        <li><%= link_to "About me", "/about_me" %></li>
        <li><a href="#">Contact</a></li>
        <% if user_signed_in? && current_user.permission_level >= 2%>
        <li class="dropdown">
          <a class="dropdown-toggle" data-toggle="dropdown" href="#">Admin</a>
          <ul class="dropdown-menu">
            <% if user_signed_in? && current_user.permission_level == 3%>
              <li><%= link_to "Dashboard", "/dashboard"%></li>
              <li><%= link_to "Nueva categoría", "/categories/new"%></li>
            <% end %>
            <li><%= link_to "Nuevo post", "/articles/new"%></li>
          </ul>
        </li>
        <%end%>

      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if @article or @comments %>
          <%if user_signed_in? %>
            <li><%= link_to "Logout", destroy_user_session_path, method: :delete, class: "fa fa-sign-out" %></li>
          <%else%>
            <li><%= link_to "Log in", new_user_session_path %></li>
            <li class="btn btn-primary" style="with:auto"><%= link_to "Sign up", "users/sign_up" %></li>
          <%end%>
        <%end%>
      </ul>
    </div>
  </div>
</nav>

app/views/partials/_searchbar.html.erb
<!--<div class="card my-4">
  <h5 class="card-header">Search</h5>
  <div class="card-body">
    <div class="input-group">
      <input type="text" class="form-control" placeholder="Search for...">
      <span class="input-group-btn">
        <button class="btn btn-secondary" type="button">Go!</button>
      </span>
    </div>
  </div>
</div>-->

app/views/partials/_sideW.html.erb
<div class="card my-4">
  <h5 class="card-header">Blog</h5>
  <div class="card-body">
    En este blog podrás encontrar información sobre tecnología, programación, mundo geek, y cosas random!
    <br><br>
    Enjoy!
  </div>
</div>